//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGED_3.CRM.Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHARSAT-PC\\PHARSATSQL;Initial Catalog=SID_2;Integrated Security=True")]
        public string Local {
            get {
                return ((string)(this["Local"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=xo6zq4as64.database.windows.net,1433;Initial Catalog=SID_2;Persist Se" +
            "curity Info=True;User ID=DB3894_ADMIN@xo6zq4as64;Password=abc123_*")]
        public string Externa {
            get {
                return ((string)(this["Externa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("areatecnica@easyprocesscompany.com")]
        public string SmtpClientCredencialUsuario {
            get {
                return ((string)(this["SmtpClientCredencialUsuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CristianFelipe")]
        public string SmtpClientCredencialContrasena {
            get {
                return ((string)(this["SmtpClientCredencialContrasena"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SmtpClientPuerto {
            get {
                return ((int)(this["SmtpClientPuerto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string SmtpClientHost {
            get {
                return ((string)(this["SmtpClientHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmtpClientSSL {
            get {
                return ((bool)(this["SmtpClientSSL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("areatecnica@easyprocesscompany.com")]
        public string EmisorDeLosCorreos {
            get {
                return ((string)(this["EmisorDeLosCorreos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Easy Process Company")]
        public string NombreCompania {
            get {
                return ((string)(this["NombreCompania"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://siged2.azurewebsites.net/")]
        public string URLCompania {
            get {
                return ((string)(this["URLCompania"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://siged2.azurewebsites.net/Recursos/Diseno/Imagenes/PAGSLOGOTIPO.png")]
        public string URLCorreoImagen {
            get {
                return ((string)(this["URLCorreoImagen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=174.36.80.52,25000;Initial Catalog=DB7890_SID2;Persist Security Info=" +
            "True;User ID=DB7890_SID2;Password=wapreal1")]
        public string Seek {
            get {
                return ((string)(this["Seek"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:xo6zq4as64.database.windows.net,1433;Initial Catalog=SID_2;Persis" +
            "t Security Info=True;User ID=DB3894_ADMIN@xo6zq4as64;Password=abc123_*")]
        public string SID_2ConnectionString {
            get {
                return ((string)(this["SID_2ConnectionString"]));
            }
        }
    }
}
